#!/usr/bin/env python3
"""Cut the Task Tracker projects-list skin assets out of the concept mock.

Produces src/tt_projects_sprites.js with:
  wordmark  - the SUNRISE CONSTRUCTION logo, background keyed to alpha (PNG)
  sites[]   - the three night-time site illustrations used as card art (JPEG)

Usage: python3 scripts/extract_projects_skin.py [mock.png]
"""
import sys, os, base64, io
import numpy as np, cv2
from PIL import Image

MOCK = sys.argv[1] if len(sys.argv) > 1 else '/root/.claude/uploads/5b79f514-cf32-595c-bb1c-cf2c8443988f/b6269ae3-image.png'
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'tt_projects_sprites.js')
img = cv2.imread(MOCK); assert img is not None, MOCK

def b64(data): return base64.b64encode(data).decode()

# --- wordmark: key the near-black navy canvas (and its faint contour lines) to alpha
y0, y1, x0, x1 = 52, 158, 84, 458
crop = img[y0:y1, x0:x1].astype(np.float32)
bg = np.median(np.concatenate([crop[:4].reshape(-1, 3), crop[-4:].reshape(-1, 3)]), 0)
d = np.sqrt(((crop - bg) ** 2).sum(-1))
alpha = np.clip((d - 22) / 40, 0, 1)
alpha = cv2.GaussianBlur(alpha, (0, 0), 0.6)
rgb = np.clip((crop - (1 - alpha[..., None]) * bg) / np.maximum(alpha[..., None], 0.05), 0, 255)
rgba = np.dstack([rgb[..., 2], rgb[..., 1], rgb[..., 0], alpha * 255]).astype(np.uint8)
im = Image.fromarray(rgba, 'RGBA').quantize(colors=160, method=Image.Quantize.FASTOCTREE)
buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
wordmark = dict(w=x1 - x0, h=y1 - y0, uri='data:image/png;base64,' + b64(buf.getvalue()))
print('wordmark', wordmark['w'], wordmark['h'], len(buf.getvalue()))

# --- site illustrations (one per mock card), JPEG
sites = []
for (ty0, ty1) in [(246, 540), (568, 864), (893, 1189)]:
    c = img[ty0:ty1, 28:452]
    ok, enc = cv2.imencode('.jpg', c, [cv2.IMWRITE_JPEG_QUALITY, 80]); assert ok
    sites.append('data:image/jpeg;base64,' + b64(enc.tobytes()))
    print('site', c.shape, len(enc))

with open(OUT, 'w') as f:
    f.write('/* Generated by scripts/extract_projects_skin.py from the projects-list concept mock.\n')
    f.write('   Card art and the wordmark used by the Task Tracker projects list. */\n')
    f.write('export const PROJECT_ART = {\n')
    f.write("  wordmark: { w: %d, h: %d, uri: '%s' },\n" % (wordmark['w'], wordmark['h'], wordmark['uri']))
    f.write("  sites: [\n" + ''.join("    '%s',\n" % s for s in sites) + "  ],\n")
    f.write('};\n')
print('wrote', OUT, os.path.getsize(OUT))
