#!/usr/bin/env bash
# Fetch the latin woff2 files the app embeds (so the Android build and the
# standalone demo render the same type offline). Writes src/fonts/*.woff2
# and src/fonts.css.
set -euo pipefail
cd "$(dirname "$0")/.."
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
URL="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow:wght@300;400;600&family=Barlow+Condensed:wght@400;600;700&display=swap"
curl -sSL -A "$UA" "$URL" -o /tmp/app-fonts.css
python3 - <<'PY'
import re, subprocess, os
css = open('/tmp/app-fonts.css').read()
blocks = re.findall(r'/\* (\w+) \*/\s*@font-face \{(.*?)\}', css, re.S)
out = []
for subset, body in blocks:
    if subset != 'latin': continue
    fam = re.search(r"font-family: '([^']+)'", body).group(1)
    wt = re.search(r'font-weight: (\d+)', body).group(1)
    url = re.search(r'url\((https://[^)]+)\)', body).group(1)
    name = fam.replace(' ', '') + '-' + wt + '.woff2'
    path = os.path.join('src/fonts', name)
    subprocess.check_call(['curl', '-sSL', '-o', path, url])
    out.append(f"@font-face {{ font-family: '{fam}'; font-style: normal; font-weight: {wt}; font-display: swap; src: url(./fonts/{name}) format('woff2'); }}")
    print(name, os.path.getsize(path))
open('src/fonts.css', 'w').write('/* generated by scripts/fetch_fonts.sh — latin subsets of the app fonts, embedded so the APK and the demo render offline */\n' + '\n'.join(out) + '\n')
PY
